Repository AztecGameLab/LongTermGame7, pull requests merged in 2023-01, with the labels that each got.

#55 Sample Scene Vegetation
  Assets/Resources/Sprites/Sample Scene Fauna Sprites/Forest-Bush1.png
  Assets/Resources/Sprites/Sample Scene Fauna Sprites/Forest-Flower-Sprite.png
  Assets/Resources/Sprites/Sample Scene Fauna Sprites/Forest-FlowerBush1.png
  Assets/Resources/Sprites/Sample Scene Fauna Sprites/Forest-bush2.png
  Assets/Resources/Sprites/Sample Scene Fauna Sprites/Forest-flowergrass1.png
  Assets/Resources/Sprites/Sample Scene Fauna Sprites/Forest-grass1.png
  Assets/Resources/Sprites/Sample Scene Fauna Sprites/Forest-grass2.png
Labels: art

#78 https://github.com/AztecGameLab/LongTermGame7/issues/60
  Assets/Editor.meta
  Assets/Editor/Windows.meta
  Assets/Editor/Windows/Sprite.meta
  Assets/Editor/Windows/Sprite/Default_One_Sided_Material.mat
  Assets/Editor/Windows/Sprite/Default_One_Sided_Material.mat.meta
  Assets/Editor/Windows/Sprite/Default_Two_Sided_Material.mat
  Assets/Editor/Windows/Sprite/Default_Two_Sided_Material.mat.meta
  Assets/Editor/Windows/Sprite/SpriteToGameObjectEditor.cs
  Assets/Editor/Windows/Sprite/SpriteToGameObjectEditor.cs.meta
  Assets/Graphics/Monsters/Artichokie_2_Material.mat
  Assets/Graphics/Monsters/Artichokie_2_Material.mat.meta
Labels: tool

#85 Player movement script with acceleration, deceleration and reactivity
  .vsconfig
  Assets/Input.meta
  Assets/Input/PlayerInput.inputactions
  Assets/Input/PlayerInput.inputactions.meta
  Assets/Scenes.meta
  Assets/Scenes/DomTesting.unity
  Assets/Scenes/DomTesting.unity.meta
  Assets/Scripts/Player.meta
  Assets/Scripts/Player/Movement.meta
  Assets/Scripts/Player/Movement/PlayerMovement.cs
  Assets/Scripts/Player/Movement/PlayerMovement.cs.meta
Labels: programming

#105 Forest Sprites
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/ShadeForest_SpikeBall.PNG
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/ShadeForest_StripedFungi.PNG
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/ShadeForest_YellowFungi.PNG
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/ShadeForest_YellowMushrooms.PNG
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/VillageFarm_Cauliflower1.PNG
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/VillageFarm_Cauliflower2.PNG
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/VillageFarm_PurpleBarley1.PNG
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/VillageFarm_PurpleBarley2.PNG
Labels: art

#106 Added more sprites to the art scene demo
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/ShadeForest_SpikeBall.mat
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/ShadeForest_SpikeBall.mat.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/ShadeForest_StripedFungi.mat
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/ShadeForest_StripedFungi.mat.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/ShadeForest_YellowFungi.mat
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/ShadeForest_YellowFungi.mat.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/ShadeForest_YellowMushrooms.mat
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/ShadeForest_YellowMushrooms.mat.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/VillageFarm_Cauliflower1.mat
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/VillageFarm_Cauliflower1.mat.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/VillageFarm_Cauliflower2.mat
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/VillageFarm_Cauliflower2.mat.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/VillageFarm_PurpleBarley1.mat
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/VillageFarm_PurpleBarley1.mat.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/VillageFarm_PurpleBarley2.mat
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/Materials/VillageFarm_PurpleBarley2.mat.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/ShadeForest_SpikeBall.PNG.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/ShadeForest_StripedFungi.PNG.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/ShadeForest_YellowFungi.PNG.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/ShadeForest_YellowMushrooms.PNG.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/VillageFarm_Cauliflower1.PNG.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/VillageFarm_Cauliflower2.PNG.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/VillageFarm_PurpleBarley1.PNG.meta
  Assets/Graphics/Environment/Sprites/ForestFaunaSprites/VillageFarm_PurpleBarley2.PNG.meta
  Assets/Levels/ArtDemo/ArtDemo.unity
  Assets/Prefab/ShadePant SpikeBall.prefab
  Assets/Prefab/ShadePant SpikeBall.prefab.meta
  Assets/Prefab/ShadePlant StripedFungi.prefab
  Assets/Prefab/ShadePlant StripedFungi.prefab.meta
  Assets/Prefab/ShadePlant YellowFungi.prefab
  Assets/Prefab/ShadePlant YellowFungi.prefab.meta
  Assets/Prefab/ShadePlant YellowMushrooms.prefab
  Assets/Prefab/ShadePlant YellowMushrooms.prefab.meta
  Assets/Prefab/Village PurpleBarely.prefab
  Assets/Prefab/Village PurpleBarely.prefab.meta
  Assets/Prefab/Village PurpleBarelySmall.prefab
  Assets/Prefab/Village PurpleBarelySmall.prefab.meta
  Assets/Prefab/VillageFarm Cauliflower.prefab
  Assets/Prefab/VillageFarm Cauliflower.prefab.meta
  Assets/Prefab/VillageFram SmallCauliflower.prefab
  Assets/Prefab/VillageFram SmallCauliflower.prefab.meta
Labels: art
